In [1]:
from all_needed_modules import *
from all_FFOPT_classes import *
import warnings
warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)

system tools imported
basic tools imported
chemistry tools imported
ML  imported
all modules and data extracted

In [2]:
#THIS ARE ALL INFORMATIONS THAT WILL BE MOVED AND SHOULD BELONG IN A STRUCTURE_INFORMATION.PY FILE
Structure_name = 'GF334'
structure_carfile = './data/GF334_v2/GF334.car'
structure_mdffile = './data/GF334_v2/GF334.mdf'
DFT_ref_path = './data/GF334_v2/DFT_reference'
GMX_ref_path = '/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical'
charge_file = '/home/uccaset/Scratch/FFOPTI/data/GF334_v2/REPEAT_charges.resp'
groupid='MOF'
atom_types = ['Zn3', 'C_2', 'C_1', 'H_', 'N_R']  # fixed order is important
train = ['lj']
size = [26.494, 26.494, 29.203]
reference_force_field = 'D2'

In [3]:
#information extraction
Structure = About_Structure(name=Structure_name, carfile=structure_carfile, mdffile=structure_mdffile, chargefile=charge_file)
DFT_ref = DFT_reference(Structure, Structure_name, DFT_ref_path, structure_file='GF334.pdb')
GMX_ref = GMX_read_reference(Structure_name, GMX_ref_path)
initial_opti_info = ParOpti_preparation(Structure_name,Structure, DFT_ref_path, GMX_ref_path)
#Obtaining the initial GMX parameters
param = GMX_ref.ref_FF_parameters()
print('information obtained')

Obtained force field parameters for 4 unique parameter sets.
information obtained

In [4]:
#GETTING TRAJECTORIES
traj_dcd_path = f'{DFT_ref_path}/md-pos-1.dcd'
frame_list = read(traj_dcd_path, index=':') #turning each frames into ase objects
# reading indx list
with open(f"{GMX_ref_path}/ffopti_backup/numbers.json", "r") as f:
    indx = json.load(f)
frames = [frame_list[i] for i in indx]

ref = frames[0] #choosing a reference frame for NVT to set PBC and cell dimensions

for atoms in frames:
    atoms.set_cell(size)
    atoms.set_pbc(True)
    atoms.wrap()  # optional, wraps positions inside box
n_of_types = Structure.atom_types()

In [5]:
order = ['lj', 'bond', 'angle', 'dihedral']

In [6]:
flattened_parameter = []
all_indices = []

for a, l1 in enumerate(list(param)):

    # enforce ordering regardless of input
    active = [x for x in order if x in train]

    parts = []
    indices = {}
    offset = 0

    for key in active:

        if key == 'lj':
            arr = param[f'{l1}']['lj'][['sigma', 'epsilon']].to_numpy().ravel()
            parts.append(arr)

            n = len(arr)
            if 'lj_sigma' not in indices:
                indices['lj_sigma']   = list(range(offset, offset+n, 2))
                indices['lj_epsilon'] = list(range(offset+1, offset+n, 2))
            offset += n

        elif key == 'bond':
            arr = param[f'{l1}']['bonds'][['length', 'force_const']].to_numpy().ravel()
            parts.append(arr)

            n = len(arr)
            if 'bond_rij' not in indices:
                indices['bond_rij'] = list(range(offset, offset+n, 2))
                indices['bond_kij'] = list(range(offset+1, offset+n, 2))
            offset += n

        elif key == 'angle':
            arr = param[f'{l1}']['angles'][['angle', 'force_const']].to_numpy().ravel()
            parts.append(arr)

            n = len(arr)
            if 'angle_angle' not in indices:
                indices['angle_angle'] = list(range(offset, offset+n, 2))
                indices['angle_kijk'] = list(range(offset+1, offset+n, 2))
            offset += n

        elif key == 'dihedral':
            arr = param[f'{l1}']['dihedrals'][['T1', 'T2', 'T3', 'T4', 'T5', 'T6']].to_numpy().ravel()
            parts.append(arr)

            n = len(arr)
            #if 'dih_T1' not in indices:
            #indices['dih_T1'] = list(range(offset, offset+n, 2))
            #indices['dih_T2'] = list(range(offset+1, offset+n, 2))
            #offset += n

    # safely concatenate
    flatie = np.concatenate(parts) if parts else np.array([])

    flattened_parameter.append(flatie)
    all_indices.append(indices)

In [7]:
len(param)

4

In [8]:
flattened_parameter

[array([0.246155, 0.5188  , 0.343085, 0.4393  , 0.343085, 0.4393  ,
        0.257113, 0.1841  , 0.326069, 0.2887  ]),
 array([0.195998, 0.0523  , 0.385   , 0.58576 , 0.355   , 0.29288 ,
        0.25    , 0.2092  , 0.325   , 0.71128 ])]

In [9]:
feature_length = len(flattened_parameter[0])
print(feature_length)

10

In [21]:
#EXTRACTING SHAPE
lj_shape = param[reference_force_field]['lj'][['sigma','epsilon']].shape
bonds_shape = param[reference_force_field]['bonds'][['length', 'force_const']].shape
angles_shape = param[reference_force_field]['angles'][['angle', 'force_const']].shape
#dihedrals_shape = param['D3']['dihedrals'][['periodicity', 'phase', 'force_const']].shape
dihedrals_shape = param[reference_force_field]['dihedrals'][['T1', 'T2', 'T3','T4', 'T5', 'T6']].shape

In [11]:
#EXTRACTING THE LOSSES
file_path = f"{GMX_ref_path}/ffopti_backup/param_type_loss.pkl"
if os.path.exists(file_path):
    average_loss = pd.read_pickle(file_path)
else:
    average_loss = initial_opti_info.average_type_loss_per_D(metrics="MAPE")
    average_loss.to_pickle(f"{GMX_ref_path}/ffopti_backup/param_type_loss.pkl")

In [12]:
average_loss

            1         2
Zn3  1.416719  1.434663
C_2  6.847904  3.929089
C_1  2.623223  3.129213
H_   4.204055  3.568191
N_R  1.791548  2.376170

In [13]:
#If we did read from the pkl file, we now check if there are any losses that were not updated
D_vals_files = list(param.keys())
pkl_list = average_loss.columns

missing_param_loss = []
for a in D_vals_files:
    num=a[1:]
    if int(num) not in pkl_list:
        missing_param_loss.append(num)
print(f'{len(missing_param_loss)} missing from backup file')

for a in missing_param_loss:
    d_folder = f'{GMX_ref_path}/D{a}'
    single_calc_tools = single_loss_calc(Structure_name,Structure, DFT_ref_path,d_folder)
    new_loss = single_calc_tools.average_type_loss_per_D()
    average_loss = average_loss.join(new_loss)
    print(f'D{a}' added to average_loss list')

0 missing from backup file

In [15]:
bounds = []

lj_sigma = set(indices.get('lj_sigma', []))
lj_epsilon = set(indices.get('lj_epsilon', []))

bond_rij = set(indices.get('bond_rij', []))
bond_kij = set(indices.get('bond_kij', []))


angle_angle = set(indices.get('angle_angle', []))
angle_kijk = set(indices.get('angle_kijk', []))

#dih_t1 = set(indices.get('dih_T1', []))
#dih_t2 = set(indices.get('dih_T2', []))

for i, x in enumerate(initial_guess):

    # LJ rules
    if i in lj_sigma or i in bond_rij:
        bounds.append((0.90 * x, 1.10 * x))
    if i in lj_epsilon:
        bounds.append((0.75 * x, 1.25 * x))

    # bond rules
    if 'bond' in train and i in bond_rij:
        bounds.append((0.90 * x, 1.10 * x))
    if 'bond' in train and i in bond_kij:
        bounds.append((0.70 * x, 1.30 * x))

        
    # angle rules
    if 'angle' in train and i in angle_angle:
        bounds.append((0.90 * x, 1.10 * x))
    if 'angle' in train and i in angle_kijk:
        bounds.append((0.70 * x, 1.30 * x))

    # dihedral rules
    #if 'dihedral' in train and i in dih_T1:
        #bounds.append((0.70 * x, 1.30 * x))
    #if 'dihedral' in train and i in dih_T2:
        #bounds.append((0.70 * x, 1.30 * x))
        

    # fallback
    #if len(bounds) < i + 1:
        #bounds.append((0.95 * x, 1.05 * x))

In [53]:
y_train = np.array(y_train)          # convert list → numpy array
y_train = y_train.reshape(-1, 1)

In [56]:
    from sklearn.preprocessing import StandardScaler
    from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel
# 2. Initialize the Scalers
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()
     
    # 3. Scale the training data
    # It is vital to fit the scaler only on existing data and transform it
    X_scaled = scaler_X.fit_transform(X_train)
    y_scaled = scaler_y.fit_transform(y_train).flatten()

In [58]:
    from sklearn.preprocessing import StandardScaler
# 2. Initialize the Scalers
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()
     
    # 3. Scale the training data
    # It is vital to fit the scaler only on existing data and transform it
    X_scaled = scaler_X.fit_transform(X_train)
    y_scaled = scaler_y.fit_transform(y_train)
     
    # 4. Define and fit the GP model with an improved kernel
    # Added a WhiteKernel to account for noise in the GROMACS simulations
    #kernel = C(1.0) * Matern(length_scale=1.0, nu=1.5) + WhiteKernel(noise_level=1e-5)
    kernel = C(1.0, (1e-3, 1e4)) * Matern(
        length_scale=np.ones(feature_length),          # 8 features in X_train
        length_scale_bounds=(1e-2, 1e2),  # optimizer can tune each scale
        nu=2.5                            # smoothness of function
    ) + WhiteKernel(noise_level=1e-5)
                    
    gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10,random_state=42)
    #gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10, alpha=1e-6, normalize_y=True, random_state=42)
    gp.fit(X_scaled, y_scaled)
     
    # 5. When predicting the next sample, remember to scale the input
    # and inverse-transform the output to get physical units back
    def predict_loss(new_params):
        # Ensure input is a 2D array for the scaler
        new_params_scaled = scaler_X.transform(np.atleast_2d(new_params))
        y_pred_scaled, sigma_scaled = gp.predict(new_params_scaled, return_std=True)
        # Transform back to original units
        y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1))
        # Sigma needs scaling by the standard deviation of y
        sigma = sigma_scaled * np.sqrt(scaler_y.var_)
        return y_pred.flatten(), sigma.flatten()
    
    # NOTE: normalize_y=True fixes the ConvergenceWarning by scaling target data
    
    print("Learned kernel:", gp.kernel_)

Learned kernel: 0.198**2 * Matern(length_scale=[0.0203, 0.144, 0.0441, 52.3, 17.1, 3.42, 30.6, 16.4, 0.0558, 37.2], nu=2.5) + WhiteKernel(noise_level=0.961)

#BUILDING THE GAUSSIAN PROCESS OF BO METHOD


kernel = C(1.0, (1e-3, 1e4)) * Matern(
    length_scale=np.ones(feature_length),          # 8 features in X_train
    length_scale_bounds=(1e-2, 1e2),  # optimizer can tune each scale
    nu=2.5                            # smoothness of function
)

# NOTE: normalize_y=True fixes the ConvergenceWarning by scaling target data
gp = GaussianProcessRegressor(kernel=kernel,
                              n_restarts_optimizer=10,
                              alpha=1e-6,
                              normalize_y=True,
                              random_state=42)

gp.fit(X_train, y_train)
print("Learned kernel:", gp.kernel_)

learned_length_scales = gp.kernel_.k2.length_scale

In [59]:
D_val

2

In [17]:
# Sensitivity is inversely proportional to length scale and these allows us to screen over the most relevant parameters if we want to reduce the search-set.
sensitivities = 1.0 / learned_length_scales

print(f"--- Sensitivity Analysis ---")
print("\n".join(
    f"Variable x{i} Sensitivity: {val:.4f}"
    for i, val in enumerate(sensitivities, start=1)
))

--- Sensitivity Analysis ---
Variable x1 Sensitivity: 1.2916
Variable x2 Sensitivity: 33.2371
Variable x3 Sensitivity: 0.1403
Variable x4 Sensitivity: 0.0905
Variable x5 Sensitivity: 0.5687
Variable x6 Sensitivity: 0.0824
Variable x7 Sensitivity: 1.0588
Variable x8 Sensitivity: 0.8111
Variable x9 Sensitivity: 1.9491
Variable x10 Sensitivity: 79.1268

In [19]:
ACQ_FUNC = expected_improvement
# Direction of optimisation
def min_obj(X):
    return -ACQ_FUNC(X.reshape(1, -1), gp, np.min(y_train)) #use this if just the average

In [20]:
# Optimization Loop: Select the number of BO rounds  ---
n_iterations = 100
print("\n--- Starting Optimization ---")

for i in range(n_iterations):
    y_best = np.min(y_train)

    best_x_next = None
    max_acq = -np.inf

    # Restart optimizer to avoid local traps in acquisition surface
    for _ in range(10):
        bounds = np.array(bounds)  # shape should be (n_features, 2)
        x0 = np.random.uniform(bounds[:, 0], bounds[:, 1])
        res = minimize(min_obj, x0=x0, bounds=bounds, method='L-BFGS-B')
        if -res.fun > max_acq:
            max_acq = -res.fun
            best_x_next = res.x

print(f"Iteration {i+1}: Suggested new parameters: {best_x_next}")

--- Starting Optimization ---
Iteration 100: Suggested new parameters: [0.18075917 0.05987926 0.36738301 0.58385302 0.32331992 0.26543198
 0.2681806  0.16989995 0.3206167  0.72031594]

In [22]:
idx = 0
x = best_x_next
#LJ parameter
if 'lj' in train:
    nlj = lj_shape[0] * lj_shape[1]
    lj_new = x[idx:idx + nlj].reshape(lj_shape)
    idx += nlj

    lj_df_new = param[reference_force_field]['lj'].copy()
    lj_df_new['sigma'] = lj_new[:, 0]
    lj_df_new['epsilon'] = lj_new[:, 1]

else:
    lj_df_new = param[reference_force_field]['lj'].copy()

#Bond Parameter
if 'bond' in train:
    nbond = bonds_shape[0] * bonds_shape[1]
    bonds_new = x[idx:idx + nbond].reshape(bonds_shape)
    idx += nbond
    
    bonds_df_new = param[reference_force_field]['bonds'].copy()
    bonds_df_new['length'] = bonds_new[:, 0]
    bonds_df_new['force_const'] = bonds_new[:, 1]
else:
    bonds_df_new = param[reference_force_field]['bonds'].copy()

#angle Parameter
if 'angle' in train:
    nangle = angles_shape[0] * angles_shape[1]
    angles_new = x[idx:idx + nangle].reshape(angles_shape)
    idx += nangle
    
    angles_df_new = param[reference_force_field]['angles'].copy()
    angles_df_new['angle'] = angles_new[:, 0]
    angles_df_new['force_const'] = angles_new[:, 1]
else:
    angles_df_new = param[reference_force_field]['angles'].copy()


#angle Parameter
if 'dihedral' in train and dihedrals_shape[1] == 3:
    ndihedral = dihedrals_shape[0] * dihedrals_shape[1]
    dihedrals_new = x[idx:idx + ndihedral].reshape(dihedrals_shape)
    idx += ndihedral
    
    dihedrals_df_new = param[reference_force_field]['dihedrals'].copy()
    dihedrals_df_new['periodicity'] = dihedrals_new[:, 0]
    dihedrals_df_new['phase'] = dihedrals_new[:, 1]
    dihedrals_df_new['force_const'] = dihedrals_new[:, 2]
elif 'dihedral' in train and dihedrals_shape[1] == 6:
    ndihedral = dihedrals_shape[0] * dihedrals_shape[1]
    dihedrals_new = x[idx:idx + ndihedral].reshape(dihedrals_shape)
    idx += ndihedral
    
    dihedrals_df_new = param[reference_force_field]['dihedrals'].copy()
    dihedrals_df_new['T1'] = dihedrals_new[:, 0]
    dihedrals_df_new['T2'] = dihedrals_new[:, 1]
    dihedrals_df_new['T3'] = dihedrals_new[:, 2]
    dihedrals_df_new['T4'] = dihedrals_new[:, 3]
    dihedrals_df_new['T5'] = dihedrals_new[:, 4]
    dihedrals_df_new['T6'] = dihedrals_new[:, 5]
else:
    dihedrals_df_new = param[reference_force_field]['dihedrals'].copy()

new_D = f'D{len(list(param))+1}'
param[new_D] = {
    'lj': lj_df_new,
    'bonds': bonds_df_new,
    'angles': angles_df_new,
    'dihedrals': dihedrals_df_new
}

print(param[new_D])

{'lj':   atom func    mass  charge ptype     sigma   epsilon
0  Zn3    1  65.380     0.0     A  0.180759  0.059879
1  C_2    1  12.011     0.0     A  0.367383  0.583853
2  C_1    1  12.011     0.0     A  0.323320  0.265432
3   H_    1   1.008     0.0     A  0.268181  0.169900
4  N_R    1  14.007     0.0     A  0.320617  0.720316, 'bonds':   atom1 atom2 func  length  force_const
0   Zn3   N_R    1  0.1883    491035.36
1   C_2   C_2    1  0.1444    343088.00
2   C_2   C_1    1  0.1490    334720.00
3   C_1   N_R    1  0.1335    410032.00
4   C_1    H_    1  0.1080    284512.00
5   N_R   N_R    1  0.1320    418400.00, 'angles':   atom1 atom2 func atom3   angle  force_const
0   Zn3   N_R  C_1     1  132.60     1615.840
1   N_R   Zn3  N_R     1  109.47      301.050
2   Zn3   N_R  N_R     1  121.90     1615.840
3   C_1   C_2  C_2     1  112.70      488.273
4   C_2   C_1   H_     1  130.70      292.880
5   C_2   C_1  N_R     1  106.60      585.760
6   C_1   C_2  C_1     1  120.00      527.184
7    H_   C_1  N_R     1  121.60      292.880
8   C_1   N_R  N_R     1  113.40      468.608, 'dihedrals':    atom1 atom2 atom3 atom4 func        T1        T2         T3        T4  \
0    Zn3   N_R   C_1   C_2    3  30.33400   0.00000  -30.33400   0.00000
1    Zn3   N_R   C_1    H_    3  30.33400   0.00000  -30.33400   0.00000
2    N_R   Zn3   N_R   C_1    3   0.00000   0.00000    0.00000   0.00000
3    N_R   N_R   Zn3   N_R    3   0.00000   0.00000    0.00000   0.00000
4    Zn3   N_R   N_R   Zn3    3  30.33400   0.00000  -30.33400   0.00000
5    Zn3   N_R   N_R   C_1    3  30.33400   0.00000  -30.33400   0.00000
6    C_1   C_2   C_2   C_1    3  -4.96013   6.28646    1.30959  -2.63592
7     H_   C_1   C_2   C_2    3   0.96650   2.89951    0.00000  -3.86601
8    N_R   C_1   C_2   C_2    3  -0.76567   2.70705    4.02501  -5.96639
9    C_1   C_2   C_1    H_    3  -0.20920  -0.62760    0.00000   0.83680
10   C_1   C_2   C_1   N_R    3   2.09200   0.00000   -2.09200   0.00000
11   C_2   C_1   N_R   N_R    3   0.72592   2.17777    0.00000  -2.90370
12    H_   C_1   N_R   N_R    3  30.33400   0.00000  -30.33400   0.00000
13   C_1   N_R   N_R   C_1    3  41.84000   0.00000  -41.84000   0.00000

         T5       T6
0   0.00000  0.00000
1   0.00000  0.00000
2   0.00000  0.00000
3   0.00000  0.00000
4   0.00000  0.00000
5   0.00000  0.00000
6   0.00000  0.00000
7   0.00000  0.00000
8   0.00000  0.00000
9   0.00000  0.00000
10  0.00000  0.00000
11  0.00000  0.00000
12  0.00000  0.00000
13  0.00000  0.00000  }

In [23]:
#Setting up loop for to create initial GMX reference data
for a, l1 in enumerate(frames):
    frame_number = f'F{indx[a]}'
    D_number = new_D

    # Create the directory D*/F*D* if it doesn't exist
    folder_path = os.path.join(GMX_ref_path, D_number, f'{frame_number}{D_number}')
    os.makedirs(folder_path, exist_ok=True)

        #.gro file
    FFOPTI_tools.write_gro(Structure_name, l1, f'{folder_path}', Structure)
    param_list = param[f'{D_number}']
        #MOF.itp file
    subprocess.run(["cp", f"{GMX_ref_path}/MOF.itp", f"{folder_path}"],check=True)
        #Force_field.itp file
    FFOPTI_tools.ref_ffitp_remake(f'{folder_path}', param_list)
        #topol.top
    Structure.write_top_file(print_directory=f'{folder_path}')
        #SP.mdp
    initial_opti_info.write_mdp_file(print_directory=f'{folder_path}')
    print(f'files created for {D_number}{frame_number}')
print('initial files created')

grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1157D3/SP.mdp written
files created for D3F1157
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2869D3/SP.mdp written
files created for D3F2869
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1158D3/SP.mdp written
files created for D3F1158
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2785D3/SP.mdp written
files created for D3F2785
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2480D3/SP.mdp written
files created for D3F2480
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1731D3/SP.mdp written
files created for D3F1731
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2459D3/SP.mdp written
files created for D3F2459
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1019D3/SP.mdp written
files created for D3F1019
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F899D3/SP.mdp written
files created for D3F899
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1487D3/SP.mdp written
files created for D3F1487
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1033D3/SP.mdp written
files created for D3F1033
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1069D3/SP.mdp written
files created for D3F1069
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2918D3/SP.mdp written
files created for D3F2918
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F675D3/SP.mdp written
files created for D3F675
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1051D3/SP.mdp written
files created for D3F1051
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1783D3/SP.mdp written
files created for D3F1783
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F449D3/SP.mdp written
files created for D3F449
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F860D3/SP.mdp written
files created for D3F860
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2138D3/SP.mdp written
files created for D3F2138
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2196D3/SP.mdp written
files created for D3F2196
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1951D3/SP.mdp written
files created for D3F1951
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F3020D3/SP.mdp written
files created for D3F3020
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F166D3/SP.mdp written
files created for D3F166
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2891D3/SP.mdp written
files created for D3F2891
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1585D3/SP.mdp written
files created for D3F1585
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F286D3/SP.mdp written
files created for D3F286
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F630D3/SP.mdp written
files created for D3F630
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F951D3/SP.mdp written
files created for D3F951
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1807D3/SP.mdp written
files created for D3F1807
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1862D3/SP.mdp written
files created for D3F1862
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F245D3/SP.mdp written
files created for D3F245
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1235D3/SP.mdp written
files created for D3F1235
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F104D3/SP.mdp written
files created for D3F104
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2989D3/SP.mdp written
files created for D3F2989
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2587D3/SP.mdp written
files created for D3F2587
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1603D3/SP.mdp written
files created for D3F1603
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F173D3/SP.mdp written
files created for D3F173
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1411D3/SP.mdp written
files created for D3F1411
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2910D3/SP.mdp written
files created for D3F2910
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F625D3/SP.mdp written
files created for D3F625
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2257D3/SP.mdp written
files created for D3F2257
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2789D3/SP.mdp written
files created for D3F2789
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F669D3/SP.mdp written
files created for D3F669
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2399D3/SP.mdp written
files created for D3F2399
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F929D3/SP.mdp written
files created for D3F929
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F129D3/SP.mdp written
files created for D3F129
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F755D3/SP.mdp written
files created for D3F755
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2083D3/SP.mdp written
files created for D3F2083
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1178D3/SP.mdp written
files created for D3F1178
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1466D3/SP.mdp written
files created for D3F1466
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2222D3/SP.mdp written
files created for D3F2222
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1135D3/SP.mdp written
files created for D3F1135
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F782D3/SP.mdp written
files created for D3F782
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2992D3/SP.mdp written
files created for D3F2992
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F275D3/SP.mdp written
files created for D3F275
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F605D3/SP.mdp written
files created for D3F605
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2636D3/SP.mdp written
files created for D3F2636
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1938D3/SP.mdp written
files created for D3F1938
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1035D3/SP.mdp written
files created for D3F1035
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1350D3/SP.mdp written
files created for D3F1350
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1533D3/SP.mdp written
files created for D3F1533
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F281D3/SP.mdp written
files created for D3F281
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2238D3/SP.mdp written
files created for D3F2238
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F817D3/SP.mdp written
files created for D3F817
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F443D3/SP.mdp written
files created for D3F443
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1857D3/SP.mdp written
files created for D3F1857
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1628D3/SP.mdp written
files created for D3F1628
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1320D3/SP.mdp written
files created for D3F1320
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2492D3/SP.mdp written
files created for D3F2492
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1886D3/SP.mdp written
files created for D3F1886
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F445D3/SP.mdp written
files created for D3F445
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1300D3/SP.mdp written
files created for D3F1300
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2063D3/SP.mdp written
files created for D3F2063
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F472D3/SP.mdp written
files created for D3F472
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2417D3/SP.mdp written
files created for D3F2417
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F112D3/SP.mdp written
files created for D3F112
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F697D3/SP.mdp written
files created for D3F697
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2714D3/SP.mdp written
files created for D3F2714
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F67D3/SP.mdp written
files created for D3F67
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F561D3/SP.mdp written
files created for D3F561
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1433D3/SP.mdp written
files created for D3F1433
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F172D3/SP.mdp written
files created for D3F172
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1667D3/SP.mdp written
files created for D3F1667
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2090D3/SP.mdp written
files created for D3F2090
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1166D3/SP.mdp written
files created for D3F1166
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2268D3/SP.mdp written
files created for D3F2268
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F768D3/SP.mdp written
files created for D3F768
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1034D3/SP.mdp written
files created for D3F1034
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F185D3/SP.mdp written
files created for D3F185
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1685D3/SP.mdp written
files created for D3F1685
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2218D3/SP.mdp written
files created for D3F2218
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1430D3/SP.mdp written
files created for D3F1430
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1810D3/SP.mdp written
files created for D3F1810
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F701D3/SP.mdp written
files created for D3F701
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F894D3/SP.mdp written
files created for D3F894
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F423D3/SP.mdp written
files created for D3F423
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2028D3/SP.mdp written
files created for D3F2028
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2668D3/SP.mdp written
files created for D3F2668
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F624D3/SP.mdp written
files created for D3F624
grofile created
force_field.itp file printed
topol.top file printed
/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F759D3/SP.mdp written
files created for D3F759
initial files created

In [24]:
new_D

'D3'

In [26]:
tools = FFOPTI_tools()
tools.job_script_mpi(Structure_name, GMX_ref_path, new_D, indx)
print('submitted')
subprocess.run(["bash", "-l", f'{GMX_ref_path}/{new_D}/run_all'],check=True)

/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/run_all written
submitted

Unloading compilers/gnu/10.2.0
  Unloading dependent: cp2k/8.2/ompi/gnu-10.2.0 mpi/openmpi/4.0.5/gnu-10.2.0
Unloading compilers/intel/2018/update3
  Unloading dependent: gromacs/2019.3/plumed/intel-2018 plumed/2.5.2/intel-2018

Unloading gcc-libs/10.2.0
  Unloading dependent: flex/2.5.39 libmatheval/1.1.11
    openblas/0.3.13-openmp/gnu-10.2.0 ucx/1.9.0/gnu-10.2.0
    binutils/2.36.1/gnu-10.2.0
Unloading compilers/gnu/10.2.0
  Unloading dependent: cp2k/8.2/ompi/gnu-10.2.0 mpi/openmpi/4.0.5/gnu-10.2.0
                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1157D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1590526093
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -663873065
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The best part of winter in Stockholm is going to Australia" (Mark Abraham)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1157D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      133.380        3.708     3597.1
                 (ns/day)    (hour/ns)
Performance:        0.023     1029.983

GROMACS reminds you: "Oh My God ! It's the Funky Shit" (Beastie Boys)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1157D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Scientists do not join hands every Sunday and sing "Yes gravity is real! I know gravity is real! I will have faith! I believe in my heart that what goes up, up, up must come down, down, down. Amen!" If they did, we would think they were pretty insecure about the concept." (Dan Barker)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2869D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1189019805
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1525760620
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Every Sperm is Sacred" (Monty Python)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2869D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      122.767        3.411     3599.6
                 (ns/day)    (hour/ns)
Performance:        0.025      947.366

GROMACS reminds you: "C has the power of assembly language and the convenience of... assembly language." (Dennis Ritchie)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2869D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "You should never bet against anything in science at odds of more than about 10^12 to 1." (Ernest Rutherford)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1158D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -88089586
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1583197462
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You still have to climb to the shoulders of the giants" (Vedran Miletic)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1158D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      119.686        3.394     3526.0
                 (ns/day)    (hour/ns)
Performance:        0.025      942.893

GROMACS reminds you: "A computer without COBOL and FORTRAN is like a piece of chocolate cake without ketchup or mustard." (Unix fortune program)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1158D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Ludwig Boltzmann, who spent much of his life studying statistical mechanics, died in 1906, by his own hand. Paul Ehrenfest, carrying on the same work, died similarly in 1933. Now it is our turn to study statistical mechanics. Perhaps it will be wise to approach the subject cautiously." (David Goodstein)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2785D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1780143449
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1020839551
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Shit Happens" (Pulp Fiction)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2785D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 20 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      134.971        3.750     3599.7
                 (ns/day)    (hour/ns)
Performance:        0.023     1041.529

GROMACS reminds you: "It is unfortunate that the authors did not make better use of all the electric power energy that went into these massive computations." (An anonymous referee)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2785D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "That Was Really Cool" (Butthead)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2480D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1300370319
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1368319705
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I Am Testing Your Grey Matter" (Red Hot Chili Peppers)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2480D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      129.024        3.588     3596.0
                 (ns/day)    (hour/ns)
Performance:        0.024      996.655

GROMACS reminds you: "It Was My Pleasure" (Pulp Fiction)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2480D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I Solve Problems" (Pulp Fiction)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1731D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1422141556
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1299738191
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "If I have not seen as far as others, it is because giants were standing on my shoulders." (Hal Abelson)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1731D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      133.219        3.701     3599.6
                 (ns/day)    (hour/ns)
Performance:        0.023     1028.048

GROMACS reminds you: "RTFM" (B. Hess)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1731D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Raw data is like raw sewage, it requires some processing before it can be spread around. The opposite is true of theories." (Jim Carr)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2459D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 903298971
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 991706094
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "There's Still Time to Change the Road You're On" (Led Zeppelin)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2459D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

               Core t (s)   Wall t (s)        (%)
       Time:      309.817        8.608     3599.2
                 (ns/day)    (hour/ns)
Performance:        0.010     2391.101

GROMACS reminds you: "I'm no model lady. A model's just an imitation of the real thing." (Mae West)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2459D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Heavier-than-air flying machines are impossible." (Lord Kelvin, President of Royal Society, 1895.)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1019D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 48098199
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -2006808812
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "It's Coming Right For Us !" (South Park)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1019D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      122.440        3.401     3599.6
                 (ns/day)    (hour/ns)
Performance:        0.025      944.847

GROMACS reminds you: "In the End Science Comes Down to Praying" (P. v.d. Berg)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1019D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Restraint! What possible restraint?" (Joseph Conrad)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F899D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1358772971
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1598581672
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

GROMACS reminds you: "Just a Minute While I Reinvent Myself" (Red Hot Chili Peppers)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F899D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      159.339        4.428     3598.3
                 (ns/day)    (hour/ns)
Performance:        0.020     1230.044

GROMACS reminds you: "Today we're not going to optimize our CUDA code, cause that's just a rabbit hole of misery!" (Tim Warburton)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F899D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Don't You Wish You Never Met Her, Dirty Blue Gene?" (Captain Beefheart)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1487D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1224249807
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1286206896
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You Dirty Switch, You're On Again" (The Breeders)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1487D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      114.705        3.187     3599.6
                 (ns/day)    (hour/ns)
Performance:        0.027      885.161

GROMACS reminds you: "Dreams seldom materialize on their own." (Dian Fossey)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1487D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "In this house, we OBEY the laws of thermodynamics!" (Homer Simpson)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1033D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1988000114
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1183850427
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Meet Me At the Coffee Shop" (Red Hot Chili Peppers)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1033D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 17 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       86.473        2.413     3583.5
                 (ns/day)    (hour/ns)
Performance:        0.036      670.309

GROMACS reminds you: "He's using code that only you and I know" (Kate Bush)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1033D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Screw a Lightbulb in your Head" (Gogol Bordello)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1069D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 981135905
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1334109863
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

GROMACS reminds you: "I try to identify myself with the atoms... I ask what I would do If I were a carbon atom or a sodium atom." (Linus Pauling)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1069D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 12 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      162.041        4.502     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.019     1250.492

GROMACS reminds you: "If it's all right with Dirac, it's all right with me." (Enrico Fermi, on being told that there was experimental evidence He-3 nuclei obey Fermi-Dirac statistics.)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1069D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If all else fails, immortality can always be assured by spectacular error." (John Kenneth Galbraith)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2918D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1987315611
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 238560867
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The Wheels On the Bus Go Round and Round" (J. Richman)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2918D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       82.710        2.298     3598.8
                 (ns/day)    (hour/ns)
Performance:        0.038      638.403

GROMACS reminds you: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight." (Bill Gates)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2918D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The best way to obtain plausible negative examples is to run a docking program with a biophysics-based function." (Julie Bernauer)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F675D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1109165840
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1827676342
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Pump Up the Volume Along With the Tempo" (Jazzy Jeff)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F675D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 28 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.600        2.115     3574.3
                 (ns/day)    (hour/ns)
Performance:        0.041      587.536

GROMACS reminds you: "This simulation is not as the former." (Malvolio, Act II, scene V of Shaphespeare's Twelfth Night)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F675D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "You Could Make More Money As a Butcher" (F. Zappa)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1051D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1602299453
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1655799351
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Ubiquitin's just a rock" (Berk Hess)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1051D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.875        1.803     3598.6
                 (ns/day)    (hour/ns)
Performance:        0.048      500.776

GROMACS reminds you: "When It Starts to Start It'll Never Stop" (Magnapop)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1051D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Alas, You're Welcome" (Prof. Dumbledore in Potter Puppet Pals)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1783D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 18599304
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1067846603
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The future always gets twisted and turned" (Lisa o Piu)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1783D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 30 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       82.787        2.300     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.038      638.921

GROMACS reminds you: "This isn't right. This isn't even wrong." (Wolfgang Pauli)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1783D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "A robot will be truly autonomous when you instruct it to go to work and it decides to go to the beach instead." (Brad Templeton)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F449D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1980496822
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1580972459
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "When you get right down to it, almost every explanation Man came up with for anything until about 1926 was stupid." (Dave Barry)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F449D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 15 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.216        2.201     3599.2
                 (ns/day)    (hour/ns)
Performance:        0.039      611.365

GROMACS reminds you: "Why would the backup server database get corrupted anyway?" (Stefan Fleischmann -- system administrator, physicist, optimist.)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F449D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Boom Boom Boom Boom, I Want You in My Room" (Venga Boys)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F860D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1403782030
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 912025997
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Contemplating answers that could break my bonds." (Peter Hammill)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F860D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 23 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.303        2.204     3598.7
                 (ns/day)    (hour/ns)
Performance:        0.039      612.127

GROMACS reminds you: "I'd Like Monday Mornings Better If They Started Later" (Garfield)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F860D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "These Gromacs Guys Really Rock" (P.J. Meulenhoff)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2138D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 526939687
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 694784960
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Perl: The only language that looks the same before and after RSA encryption." (Keith Bostic)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2138D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 23 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.469        2.208     3598.7
                 (ns/day)    (hour/ns)
Performance:        0.039      613.411

GROMACS reminds you: "They Paint Their Faces So Differently From Ours" (Gogol Bordello)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2138D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Ludwig Boltzmann, who spent much of his life studying statistical mechanics, died in 1906, by his own hand. Paul Ehrenfest, carrying on the same work, died similarly in 1933. Now it is our turn to study statistical mechanics. Perhaps it will be wise to approach the subject cautiously." (David Goodstein)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2196D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1209828682
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1909270821
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "If you want to save your child from polio, you can pray or you can inoculate... choose science." (Carl Sagan)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2196D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 29 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       97.762        2.728     3584.3
                 (ns/day)    (hour/ns)
Performance:        0.032      757.648

GROMACS reminds you: "Take away paradox from the thinker and you have a professor." (Soren Kirkegaard)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2196D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Where all think alike, no one thinks very much." (Walter Lippmann)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1951D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1759545802
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -95181557
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Ease Myself Into the Body Bag" (P.J. Harvey)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1951D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 24 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       89.985        2.500     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.035      694.474

GROMACS reminds you: "Jesus Built My Hotrod" (Ministry)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1951D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The future always gets twisted and turned" (Lisa o Piu)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F3020D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1654686015
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -593562890
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Naive you are if you believe life favours those who aren't naive." (Piet Hein)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F3020D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 23 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.241        2.201     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.039      611.515

GROMACS reminds you: "We All Get the Flu, We All Get Aids" (LIVE)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F3020D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I ought to warn you, I have no faith" (Jane Eyre in Jane Eyre by Charlotte Bronte)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F166D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1234140018
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 801461470
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Come on boys, Let's push it hard" (P.J. Harvey)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F166D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 20 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.211        2.089     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.041      580.416

GROMACS reminds you: "If it's all right with Dirac, it's all right with me." (Enrico Fermi, on being told that there was experimental evidence He-3 nuclei obey Fermi-Dirac statistics.)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F166D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Let's Go Hang Out In a Mall" (LIVE)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2891D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1236498928
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1258483199
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "No matter how important you are, you are not as important as lunch." (Randy Pausch)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2891D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 27 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.607        2.101     3598.9
                 (ns/day)    (hour/ns)
Performance:        0.041      583.560

GROMACS reminds you: "Push It Real Good" (Salt 'n' Pepa)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2891D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "In the End Science Comes Down to Praying" (P. v.d. Berg)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1585D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1586588646
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -119636347
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Academe, n.: An ancient school where morality and philosophy were taught. Academy, n.: A modern school where football is taught." (Ambrose Bierce)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1585D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       97.181        2.700     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.032      749.999

GROMACS reminds you: "It's just the way this stuff is done" (Built to Spill)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1585D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Occams Razor is the scientific principle that, all things being equal, the simplest explanation is always the dog ate my homework." (Greg Tamblyn)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F286D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -944645138
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -672145884
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Studying expands knowledge. Knowledge is power. Power corrupts. Corruption is a crime. Crime doesn't pay." (Anonymous)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F286D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.110        2.003     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.043      556.486

GROMACS reminds you: "One Cross Each" (Monty Python)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F286D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The best part of winter in Stockholm is going to Australia" (Mark Abraham)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F630D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -69770501
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -473721071
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I love deadlines. I like the whooshing sound they make as they fly by." (Douglas Adams)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F630D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       97.277        2.717     3580.3
                 (ns/day)    (hour/ns)
Performance:        0.032      754.728

GROMACS reminds you: "Academe, n.: An ancient school where morality and philosophy were taught. Academy, n.: A modern school where football is taught." (Ambrose Bierce)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F630D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Restraint! What possible restraint?" (Joseph Conrad)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F951D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 361735474
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 783348108
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The Carpenter Goes Bang Bang" (The Breeders)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F951D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.718        2.104     3598.7
                 (ns/day)    (hour/ns)
Performance:        0.041      584.451

GROMACS reminds you: "Ludwig Boltzmann, who spent much of his life studying statistical mechanics, died in 1906, by his own hand. Paul Ehrenfest, carrying on the same work, died similarly in 1933. Now it is our turn to study statistical mechanics. Perhaps it will be wise to approach the subject cautiously." (David Goodstein)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F951D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "You always pass failure on the way to success." (Mickey Rooney)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1807D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -77566911
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 192373385
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "... an excellent man, almost worthy of such a wife ..." (Jane Eyre in Jane Eyre by Charlotte Bronte)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1807D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 15 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.677        2.121     3568.8
                 (ns/day)    (hour/ns)
Performance:        0.041      589.032

GROMACS reminds you: "You Fill Your Space So Sweet" (F. Apple)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1807D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The Feeling of Power was Intoxicating, Magic" (Frida Hyvonen)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1862D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 616467818
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1742651958
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I Live the Life They Wish They Did" (Tricky)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1862D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       97.162        2.699     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.032      749.818

GROMACS reminds you: "Don't pay any attention to what they write about you. Just measure it in inches." (Andy Warhol)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1862D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The time for theory is over" (J. Hajdu)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F245D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 651279176
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 244621361
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The Feeling of Power was Intoxicating, Magic" (Frida Hyvonen)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F245D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 20 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       71.977        2.001     3597.7
                 (ns/day)    (hour/ns)
Performance:        0.043      555.735

GROMACS reminds you: "You Could Make More Money As a Butcher" (F. Zappa)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F245D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Computer science is no more about computers than astronomy is about telescopes" (Edsger Dijkstra)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1235D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1852580092
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1027638171
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Take Dehydrated Water On Your Desert Trips" (Space Quest III)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1235D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       82.427        2.291     3598.0
                 (ns/day)    (hour/ns)
Performance:        0.038      636.360

GROMACS reminds you: "That Was Really Cool" (Butthead)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1235D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Shoot them in the back now" (The Ramones)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F104D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -211304151
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1091692251
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I can’t go to a restaurant and order food because I keep looking at the fonts on the menu. Five minutes later I realize that it’s also talking about food." (Donald Knuth)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F104D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.183        2.200     3599.1
                 (ns/day)    (hour/ns)
Performance:        0.039      611.126

GROMACS reminds you: "Njuta men inte frossa, springa men inte fly" (Paganus)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F104D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "A tidy laboratory means a lazy chemist." (J.J. Berzelius)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2989D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 2061681493
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -845239683
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "With a Little Penknife" (Nick Cave)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2989D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       89.970        2.500     3598.9
                 (ns/day)    (hour/ns)
Performance:        0.035      694.428

GROMACS reminds you: "Let's Go Hang Out In a Mall" (LIVE)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2989D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Does college pay? They do if you are a good open-field runner." (Will Rogers)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2587D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1518901016
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -96084665
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You still have to climb to the shoulders of the giants" (Vedran Miletic)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2587D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 33 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       86.406        2.400     3599.6
                 (ns/day)    (hour/ns)
Performance:        0.036      666.794

GROMACS reminds you: "I Had So Many Problem, and Then I Got Me a Walkman" (F. Black)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2587D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If You're So Special Why aren't You Dead ?" (The Breeders)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1603D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -164411713
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -523213329
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Player Sleeps With the Fishes" (Ein Bekanntes Spiel Von ID Software)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1603D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       97.762        2.717     3598.0
                 (ns/day)    (hour/ns)
Performance:        0.032      754.753

GROMACS reminds you: "The Poodle Bites" (F. Zappa)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1603D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Problems worthy of attack prove their worth by hitting back." (Piet Hein)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F173D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 683895148
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1363409964
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "A Protein is a Set Of Coordinates" (A.P. Heiner)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F173D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       94.033        2.624     3583.6
                 (ns/day)    (hour/ns)
Performance:        0.033      728.886

GROMACS reminds you: "I Am the Psychotherapist. Please, Describe Your Problems." (GNU Emacs)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F173D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "A university faculty is 500 egotists with a common parking problem." (Keith Sullivan)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1411D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -177929889
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 275376754
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I removed all the lambda defaults so that users have to think!" (Berk Hess)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1411D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 15 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       71.790        1.994     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.043      554.007

GROMACS reminds you: "Do You Have Sex Maniacs or Schizophrenics or Astrophysicists in Your Family?" (Gogol Bordello)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1411D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Fly to the Court of England and Unfold" (Macbeth, Act 3, Scene 6, William Shakespeare)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2910D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1264342707
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -166731309
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You Don't Wanna Know" (Pulp Fiction)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2910D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.842        1.802     3598.8
                 (ns/day)    (hour/ns)
Performance:        0.048      500.493

GROMACS reminds you: "Pump Up the Volume Along With the Tempo" (Jazzy Jeff)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2910D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If I have not seen as far as others, it is because giants were standing on my shoulders." (Hal Abelson)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F625D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1238340287
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -516222859
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "In the Meantime, Take Care of Yourself aaand Eachother" (J. Springer)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F625D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 15 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       54.042        1.501     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.058      417.072

GROMACS reminds you: "Therefore, things must be learned only to be unlearned again or, more likely, to be corrected." (Richard Feynman)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F625D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "It is unfortunate that the authors did not make better use of all the electric power energy that went into these massive computations." (An anonymous referee)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2257D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -277227391
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1135601958
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Physics isn't a religion. If it were, we'd have a much easier time raising money." (Leon Lederman)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2257D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       61.204        1.700     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.051      472.338

GROMACS reminds you: "Yeah, uh uh, Neil's Head !" (Neil)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2257D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "How Do You Like Your Vacation So Far ?" (Speed 2 - Cruise Control)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2789D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -252268685
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 2065469972
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Jede der Scherben spiegelt das Licht" (Wir sind Helden)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2789D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 15 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       50.411        1.401     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.062      389.055

GROMACS reminds you: "A Protein is a Set Of Coordinates" (A.P. Heiner)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2789D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Rat-tat-tat Ka boom boom" (The Smashing Pumpkins)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F669D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 539669625
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 234607240
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I can’t go to a restaurant and order food because I keep looking at the fonts on the menu. Five minutes later I realize that it’s also talking about food." (Donald Knuth)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F669D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 24 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.586        1.795     3599.0
                 (ns/day)    (hour/ns)
Performance:        0.048      498.488

GROMACS reminds you: "I Ripped the Cord Right Out Of the Phone" (Capt. Beefheart)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F669D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Ease Myself Into the Body Bag" (P.J. Harvey)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2399D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 858546312
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -569764560
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "When the universe has expanded, time will contract" (Franz Ferdinand)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2399D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 17 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       82.773        2.300     3599.6
                 (ns/day)    (hour/ns)
Performance:        0.038      638.760

GROMACS reminds you: "What if you're wrong about the great Ju Ju at the bottom of the sea?" (Richard Dawkins)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2399D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Wedged as we are between two eternities of idleness, there is no excuse for being idle now" (Anthony Burgess)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F929D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 613737326
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 349216486
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I Should Be the Pimp Of the Year" (Urban Dance Squad)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F929D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.006        2.000     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.043      555.681

GROMACS reminds you: "The three principal virtues of a programmer are Laziness, Impatience, and Hubris" (Larry Wall)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F929D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The great tragedy of science - the slaying of a beautiful hypothesis by an ugly fact." (Thomas Henry Huxley)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F129D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1543508413
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1919449752
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Art is what you can get away with." (Andy Warhol)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F129D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 14 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.572        2.100     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.041      583.201

GROMACS reminds you: "It Was My Pleasure" (Pulp Fiction)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F129D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "It'll Cure Your Asthma Too !" (F. Zappa)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F755D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1962804883
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 377935005
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Shake Yourself" (YES)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F755D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.069        2.002     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      556.174

GROMACS reminds you: "Boom Boom Boom Boom, I Want You in My Room" (Venga Boys)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F755D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Almost without exception, the talented women I have known have believed they had less ability than they actually had. And almost without exception, the talented men I have known believed they had more." (Gregory Petsko)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2083D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1430276644
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1365183004
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "It's So Fast It's Slow" (F. Black)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2083D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.227        1.896     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.046      526.532

GROMACS reminds you: "Chemical gases filling lungs of little ones" (Black Eyed Peas)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2083D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "It's So Fast It's Slow" (F. Black)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1178D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1904747243
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 2112229277
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Praise those of your critics for whom nothing is up to standard." (Dag Hammarskjold)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1178D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 35 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       61.194        1.700     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.051      472.266

GROMACS reminds you: "With a Lead Filled Snowshoe" (F. Zappa)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1178D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "It's an easy game, just don't let the ball past!" (Szilard Pall)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1466D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1719222643
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1644754395
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Right Between the Eyes" (F. Zappa)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1466D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 30 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.041        2.001     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      555.959

GROMACS reminds you: "Occams Razor is the scientific principle that, all things being equal, the simplest explanation is always the dog ate my homework." (Greg Tamblyn)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1466D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If You're So Special Why aren't You Dead ?" (The Breeders)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2222D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -822190350
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1530111344
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "In a Deep Deep Well" (Nick Cave)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2222D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 17 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       81.476        2.264     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.038      628.759

GROMACS reminds you: "We Have No Money" (E. Clementi)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2222D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I Wonder, Should I Get Up..." (J. Lennon)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1135D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 721122005
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1952874662
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Put Me Inside SSC, Let's Test Superstring Theory, Oh Yoi Yoi Accelerate the Protons" (Gogol Bordello)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1135D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       71.993        2.000     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      555.586

GROMACS reminds you: "You still have to climb to the shoulders of the giants" (Vedran Miletic)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1135D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Scientists do not join hands every Sunday and sing "Yes gravity is real! I know gravity is real! I will have faith! I believe in my heart that what goes up, up, up must come down, down, down. Amen!" If they did, we would think they were pretty insecure about the concept." (Dan Barker)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F782D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -528074392
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1841208473
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "We Can Dance Like Iggy Pop" (Red Hot Chili Peppers)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F782D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 26 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.435        1.901     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.045      528.148

GROMACS reminds you: "Your Country Needs YOU" (U.S. Army)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F782D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Memory is like an orgasm. It’s a lot better if you don’t have to fake it." (Seymour Cray, on virtual memory)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2992D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1705634747
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 401817654
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Everything's formed from particles" (Van der Graaf Generator)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2992D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 14 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.047        1.891     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.046      525.142

GROMACS reminds you: "I believe in miracles cause I'm one" (The Ramones)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2992D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "A university faculty is 500 egotists with a common parking problem." (Keith Sullivan)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F275D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1040865481
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -966360483
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "It all works because Avogadro's number is closer to infinity than to 10." (Ralph Baierlein)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F275D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 26 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.404        1.900     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.045      527.890

GROMACS reminds you: "The Feeling of Power was Intoxicating, Magic" (Frida Hyvonen)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F275D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If at first you don't succeed, try two more times so that your failure is statistically significant." (Dallas Warren)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F605D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -910489537
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 982737117
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I like to wait, then I feel like I do something" (Carl Caleman)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F605D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 23 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       82.846        2.302     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.038      639.326

GROMACS reminds you: "There is no reason for any individual to have a computer in his home." (Ken Olsen, head of Digital Equipment Corp.)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F605D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Exactly" (Pulp Fiction)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2636D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1757928517
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -623777523
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Here are all the 'gmx' tools... but no gmx writethesis" (Christian Blau)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2636D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 26 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.107        1.892     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.046      525.609

GROMACS reminds you: "Bring Out the Gimp" (Pulp Fiction)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2636D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "What's the point, yo, what's the spread?" (Red Hot Chili Peppers)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1938D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1437887134
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -776242004
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Exactly" (Pulp Fiction)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1938D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       43.209        1.201     3599.1
                 (ns/day)    (hour/ns)
Performance:        0.072      333.486

GROMACS reminds you: "The determined Real Programmer can write FORTRAN programs in any language." (Ed Post)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1938D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "To survive science you have to become science." (Gerrit Groenhof)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1035D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 527912899
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 373778104
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Shoot them in the back now" (The Ramones)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1035D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 22 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.795        1.800     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.048      500.046

GROMACS reminds you: "Science, my lad, is made up of mistakes, but they are mistakes which it is useful to make, because they lead little by little to the truth." (Jules Verne)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1035D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The Nobel Prize is fine, but the drugs I've developed are rewards in themselves." (Gertrude Elion)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1350D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1461989483
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1914638475
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Science, my lad, is made up of mistakes, but they are mistakes which it is useful to make, because they lead little by little to the truth." (Jules Verne)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1350D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 24 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       90.408        2.512     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.034      697.700

GROMACS reminds you: "In a Deep Deep Well" (Nick Cave)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1350D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Encountered Subspace Anomaly" (Star Trek)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1533D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 753953430
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1793320458
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "If You Want Something Done You Have to Do It Yourself" (Highlander II)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1533D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 24 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       90.010        2.501     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.035      694.615

GROMACS reminds you: "Please implement proper hep writing" (GROMACS)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1533D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Why, how now, Claudio ! Whence Comes this Restraint ?" (Lucio in Measure for measure, Act 1, Scene 4, William Shakespeare)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F281D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 687692599
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -477916560
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Making merry out of nothing, like in refugee camp" (Gogol Bordello)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F281D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 31 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       57.248        1.591     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.054      441.812

GROMACS reminds you: "During my undergraduate work I concluded that electrostatics is unlikely to be important [for enzymes]" (Arieh Warshel, Nobel lecture 2013)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F281D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Statistics: The only science that enables different experts using the same figures to draw different conclusions." (Evan Esar)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2238D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 596958545
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1718298005
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You Look Better Upside Down" (Throwing Muses)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2238D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 27 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.333        2.204     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.039      612.231

GROMACS reminds you: "I removed all the lambda defaults so that users have to think!" (Berk Hess)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2238D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "You Try to Run the Universe" (Tricky)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F817D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -933745636
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1702641644
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The World is a Friendly Place" (Magnapop)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F817D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 27 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       54.008        1.501     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.058      416.809

GROMACS reminds you: "It's just B I O L O G Y, can't you see?" (Joe Jackson)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F817D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Shaken, not Stirred" (J. Bond)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F443D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 615715948
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1038912559
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I Am a Wonderful Thing" (Kid Creole)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F443D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       57.853        1.607     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.054      446.481

GROMACS reminds you: "Pump Up the Volume Along With the Tempo" (Jazzy Jeff)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F443D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I Used To Care, But Things Have Changed" (Bob Dylan)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1857D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 781672338
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 2102611019
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Just Give Me a Blip" (F. Black)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1857D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 26 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       57.219        1.590     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.054      441.594

GROMACS reminds you: "If at first you don't succeed, try two more times so that your failure is statistically significant." (Dallas Warren)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1857D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Memory is like an orgasm. It’s a lot better if you don’t have to fake it." (Seymour Cray, on virtual memory)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1628D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1784490200
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 761245106
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Wait a Minute, aren't You.... ? (gunshots) Yeah." (Bodycount)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1628D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       86.281        2.397     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.036      665.848

GROMACS reminds you: "As Always Your Logic Is Impeccable" (Tuvok)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1628D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Three Little Fonzies" (Pulp Fiction)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1320D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -318817752
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1083672448
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Naive you are if you believe life favours those who aren't naive." (Piet Hein)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1320D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 33 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.839        1.801     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.048      500.389

GROMACS reminds you: "Making merry out of nothing, like in refugee camp" (Gogol Bordello)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1320D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I Solve Problems" (Pulp Fiction)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2492D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1999741769
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1624889396
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Put Me Inside SSC, Let's Test Superstring Theory, Oh Yoi Yoi Accelerate the Protons" (Gogol Bordello)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2492D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.643        2.018     3599.2
                 (ns/day)    (hour/ns)
Performance:        0.043      560.634

GROMACS reminds you: "Catholic School Girls Rule" (Red Hot Chili Peppers)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2492D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "In physics, you don't have to go around making trouble for yourself. Nature does it for you." (Frank Wilczek)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1886D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1070780288
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -316752342
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "In a Deep Deep Well" (Nick Cave)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1886D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 30 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.398        2.011     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      558.723

GROMACS reminds you: "Don't Follow Me Home" (Throwing Muses)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1886D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Do You Have Sex Maniacs or Schizophrenics or Astrophysicists in Your Family?" (Gogol Bordello)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F445D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -188791484
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 2118712890
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The time for theory is over" (J. Hajdu)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F445D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.607        2.100     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.041      583.469

GROMACS reminds you: "'Nay. We are but men.' Rock!" (Tenacious D)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F445D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Sitting on a rooftop watching molecules collide" (A Camp)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1300D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 2030431233
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -2022193452
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Good Music Saves your Soul" (Lemmy)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1300D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 11 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.823        1.912     3598.9
                 (ns/day)    (hour/ns)
Performance:        0.045      531.211

GROMACS reminds you: "If your experiment needs a statistician, you need a better experiment." (Ernest Rutherford)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1300D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Sitting on a rooftop watching molecules collide" (A Camp)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2063D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1633001849
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 900368934
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "If your experiment needs a statistician, you need a better experiment." (Ernest Rutherford)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2063D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.001        2.000     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      555.650

GROMACS reminds you: "Never measure the height of a mountain until you have reached the top. Then you will see how low it was." (Dag Hammarskjold)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2063D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "There are only two kinds of programming languages: those people always bitch about and those nobody uses." (Bjarne Stroustrup)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F472D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -2007446933
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 543379196
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Go back to the rock from under which you came" (Fiona Apple)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F472D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 18 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.202        2.200     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.039      611.203

GROMACS reminds you: "Everybody Wants to Be Naked and Famous" (Tricky)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F472D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Carbohydrates is all they groove" (Frank Zappa)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2417D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -250591359
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 2097931322
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The best way to obtain plausible negative examples is to run a docking program with a biophysics-based function." (Julie Bernauer)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2417D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 24 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.469        2.098     3596.6
                 (ns/day)    (hour/ns)
Performance:        0.041      582.876

GROMACS reminds you: "GROMACS First : Making MD Great Again" (Vedran Miletic)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2417D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If all else fails, immortality can always be assured by spectacular error." (John Kenneth Galbraith)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F112D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1430574695
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1812032016
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "California, R.I.P." (Red Hot Chili Peppars)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F112D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       86.465        2.402     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.036      667.252

GROMACS reminds you: "It Was My Pleasure" (Pulp Fiction)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F112D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live." (Martin Golding)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F697D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 965571567
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1604527931
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "This is where we have been working hard to push down performance." (Szilard Pall, GTC 2015 talk)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F697D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.006        2.000     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      555.690

GROMACS reminds you: "First off, I'd suggest printing out a copy of the GNU coding standards, and NOT read it. Burn them, it's a great symbolic gesture." (Linus Torvalds)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F697D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "These are Ideas, They are Not Lies" (Magnapop)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2714D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -23280998
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 629012606
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You Fill Your Space So Sweet" (F. Apple)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2714D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       57.636        1.601     3598.9
                 (ns/day)    (hour/ns)
Performance:        0.054      444.860

GROMACS reminds you: "An intellectual is someone who has found something more interesting than sex." (Edgar Wallace)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2714D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "If You Don't Like Cool Quotes Check Your GMXRC File" (Your Sysadmin)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F67D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1877897772
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1592198063
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "According to my computations we're overdue for a transformation." (Jackson Browne)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F67D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 20 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.596        1.795     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.048      498.514

GROMACS reminds you: "Let's Go Hang Out In a Mall" (LIVE)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F67D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "To survive science you have to become science." (Gerrit Groenhof)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F561D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1300922696
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -574914602
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "... yet the [economic] profession continued to churn out purely theoretical results without even knowing what facts needed to be explained." (Thomas Piketty)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F561D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       67.976        1.889     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.046      524.591

GROMACS reminds you: "We Look Pretty Sharp In These Clothes" (F. Zappa)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F561D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Encountered Subspace Anomaly" (Star Trek)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1433D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 431726878
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1495022909
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

GROMACS reminds you: "The best model of a cat is another cat..., specially the same cat." (Arturo Rosenblueth)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1433D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 10 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:      172.160        4.783     3599.8
                 (ns/day)    (hour/ns)
Performance:        0.018     1328.473

GROMACS reminds you: "I used to be blond and stupid, but now I dyed it black" (Miss Li)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1433D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Just Give Me a Blip" (F. Black)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F172D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1614807139
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -704856547
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "It's So Lonely When You Don't Even Know Yourself" (Red Hot Chili Peppers)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F172D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       85.994        2.389     3599.1
                 (ns/day)    (hour/ns)
Performance:        0.036      663.696

GROMACS reminds you: "Is This the Right Room for an Argument ?" (Monty Python)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F172D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Baseball Heroes Only" (P.J. Harvey)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1667D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 2008983177
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 923634276
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Hangout In the Suburbs If You've Got the Guts" (Urban Dance Squad)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1667D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 28 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.931        2.110     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.041      585.975

GROMACS reminds you: "I believe in miracles cause I'm one" (The Ramones)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1667D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Royale With Cheese" (Pulp Fiction)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2090D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -897907306
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -655555057
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "A scientific truth does not triumph by convincing its opponents and making them see the light, but rather because its opponents eventually die and a new generation grows up that is familiar with it." (Max Planck)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2090D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 21 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       85.934        2.388     3598.8
                 (ns/day)    (hour/ns)
Performance:        0.036      663.284

GROMACS reminds you: "A scientific truth does not triumph by convincing its opponents and making them see the light, but rather because its opponents eventually die and a new generation grows up that is familiar with it." (Max Planck)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2090D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Some of these pro-drug messages come from popular culture." (John Walters)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1166D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1984998622
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1381376318
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "No great discovery was ever made without a bold guess." (Marie Curie)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1166D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 23 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.565        2.212     3597.1
                 (ns/day)    (hour/ns)
Performance:        0.039      614.429

GROMACS reminds you: "If I have not seen as far as others, it is because giants were standing on my shoulders." (Hal Abelson)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1166D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Right Now My Job is Eating These Doughnuts" (Bodycount)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2268D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1941746337
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -530892416
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "The scientist is not the person who always gives the right answers, he is the one who asks the right questions." (Claude Levi-Strauss)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2268D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 30 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       57.279        1.592     3598.3
                 (ns/day)    (hour/ns)
Performance:        0.054      442.177

GROMACS reminds you: "Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live." (Martin Golding)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2268D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Humbug! Most things free-born will submit to anything for a salary" (Mr. Rochester in Jane Eyre by Charlotte Bronte)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F768D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -976052987
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1334468193
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "My Brothers are Protons (Protons!), My Sisters are Neurons (Neurons)" (Gogol Bordello)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F768D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 33 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       54.039        1.502     3597.4
                 (ns/day)    (hour/ns)
Performance:        0.058      417.268

GROMACS reminds you: "Memory is like an orgasm. It’s a lot better if you don’t have to fake it." (Seymour Cray, on virtual memory)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F768D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I believe in miracles cause I'm one" (The Ramones)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1034D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -543243135
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 124380236
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I always seem to get inspiration and renewed vitality by contact with this great novel land of yours which sticks up out of the Atlantic." (Winston Churchill)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1034D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 29 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       61.206        1.701     3598.4
                 (ns/day)    (hour/ns)
Performance:        0.051      472.478

GROMACS reminds you: "(That makes 100 errors; please try again.)" (TeX)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1034D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Shoot them in the back now" (The Ramones)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F185D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 97424219
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 880050455
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Been There, Done It" (Beavis and Butthead)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F185D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 18 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       50.224        1.395     3599.2
                 (ns/day)    (hour/ns)
Performance:        0.062      387.617

GROMACS reminds you: "Physics is like sex: sure, it may give some practical results, but that’s not why we do it" (Richard P. Feynman)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F185D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "You Leave Me Dry" (P.J. Harvey)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1685D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 936837561
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1002204299
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I Ripped the Cord Right Out Of the Phone" (Capt. Beefheart)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1685D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 20 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       79.805        2.217     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.039      615.859

GROMACS reminds you: "Why Do *You* Use Constraints ?" (H.J.C. Berendsen)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1685D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Physics isn't a religion. If it were, we'd have a much easier time raising money." (Leon Lederman)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2218D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 88439021
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 41038781
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Pump Up the Volume Along With the Tempo" (Jazzy Jeff)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2218D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 17 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       86.440        2.401     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.036      667.060

GROMACS reminds you: "And You Will Know That My Name is the Lord When I Lay My Vengeance Upon Thee." (Pulp Fiction)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2218D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I Snipe Like Wesley" (Urban Dance Squad)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1430D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 2020246489
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1404094438
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "In ancient times they had no statistics so they had to fall back on lies." (Stephen Leacock)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1430D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 14 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.820        1.801     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.048      500.242

GROMACS reminds you: "No great discovery was ever made without a bold guess." (Marie Curie)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1430D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I Smell Smoke From a Gun Named Extinction" (Pixies)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1810D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1478511129
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -740730298
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

GROMACS reminds you: "As an adolescent I aspired to lasting fame, I craved factual certainty, and I thirsted for a meaningful vision of human life -- so I became a scientist. This is like becoming an archbishop so you can meet girls." (Matt Cartmill)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1810D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

               Core t (s)   Wall t (s)        (%)
       Time:      221.543        6.154     3599.9
                 (ns/day)    (hour/ns)
Performance:        0.014     1709.503

GROMACS reminds you: "Weaseling out of things is important to learn. It's what separates us from the animals... except the weasels." (Homer Simpson)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F1810D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "X-rays will prove to be a hoax." (Lord Kelvin, while president of the Royal Society)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F701D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1792179669
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 747023709
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "I'm a Jerk" (F. Black)

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F701D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 23 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       93.381        2.595     3598.4
                 (ns/day)    (hour/ns)
Performance:        0.033      720.849

GROMACS reminds you: "Money won't buy happiness, but it will pay the salaries of a large research staff to study the problem." (Bill Vaughan)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F701D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to build bigger and better idiots. So far, the universe is winning." (Rick Cook)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F894D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1114470029
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 688660271
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Shake Barrels Of Whisky Down My Throat" (Throwing Muses)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F894D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 19 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.608        2.101     3599.3
                 (ns/day)    (hour/ns)
Performance:        0.041      583.501

GROMACS reminds you: "May the Force Be With You" (Star Wars)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F894D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Suzy is a headbanger, her mother is a geek" (The Ramones)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F423D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1219163327
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 424016152
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "You Fill Your Space So Sweet" (F. Apple)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F423D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 14 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       75.570        2.099     3599.5
                 (ns/day)    (hour/ns)
Performance:        0.041      583.188

GROMACS reminds you: "Baby, It Aint Over Till It's Over" (Lenny Kravitz)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F423D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time." (Tom Cargill)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2028D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to -1629760219
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 1518088589
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Gabba Gabba Hey!" (The Ramones)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2028D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 17 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       64.708        1.798     3599.2
                 (ns/day)    (hour/ns)
Performance:        0.048      499.401

GROMACS reminds you: "I Used To Care, But Things Have Changed" (Bob Dylan)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2028D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Studying expands knowledge. Knowledge is power. Power corrupts. Corruption is a crime. Crime doesn't pay." (Anonymous)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2668D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 814571530
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1940681599
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "Bum Stikkie Di Bum Stikkie Di Bum Stikkie Di Bum" (R. Slijngaard)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2668D3
Command line:
  gmx_mpi mdrun -deffnm SP

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 16 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       68.413        1.901     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.045      527.964

GROMACS reminds you: "Can I have everything louder than everything else?" (Deep Purple)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F2668D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Proceed, With Fingers Crossed" (TeX)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F624D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 1309849640
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to -1457720738
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "She Says She Can't Go Home Without a Chaperone" (E. Costello)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F624D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.543        2.038     3559.7
                 (ns/day)    (hour/ns)
Performance:        0.042      566.079

GROMACS reminds you: "Bum Stikkie Di Bum Stikkie Di Bum Stikkie Di Bum" (R. Slijngaard)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F624D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "I love fools' experiments. I am always making them." (Charles Darwin)

                      :-) GROMACS - gmx grompp, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F759D3
Command line:
  gmx_mpi grompp -f SP.mdp -c GF334.gro -p topol.top -o SP.tpr -maxwarn 3


NOTE 1 [file SP.mdp]:
  Setting nstcalcenergy (100) equal to nstenergy (1)


NOTE 2 [file SP.mdp]:
  For a correct single-point energy evaluation with nsteps = 0, use
  continuation = yes to avoid constraining the input coordinates.


NOTE 3 [file SP.mdp]:
  leapfrog does not yet support Nose-Hoover chains, nhchainlength reset to 1

Setting the LD random seed to 958534031
Generated 15 of the 15 non-bonded parameter combinations
Excluding 3 bonded neighbours molecule type 'MOF'
Setting gen_seed to 104446243
Velocities were taken from a Maxwell distribution at 298 K
Removing all charge groups because cutoff-scheme=Verlet
Number of degrees of freedom in T-Coupling group System is 3237.00

WARNING 1 [file SP.mdp]:
  You are using full electrostatics treatment PME for a system without
  charges.
  This costs a lot of performance for just processing zeros, consider using
  Cut-off instead.


Estimate for the relative computational load of the PME mesh part: 0.17

There were 3 notes

There was 1 warning

GROMACS reminds you: "No, no, you're not thinking, you're just being logical." (Niels Bohr)

                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F759D3
Command line:
  gmx_mpi mdrun -deffnm SP

Reading file SP.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 100, rlist from 1.2 to 1.2

Using 1 MPI process
Using 36 OpenMP threads

Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 298 K
Calculated rlist for 1x1 atom pair-list as 1.200 nm, buffer size 0.000 nm
Set rlist, assuming 4x4 atom pair-list, to 1.200 nm, buffer size 0.000 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 24x24x25, spacing 0.110 0.110 0.117
This run will generate roughly 0 Mb of data

starting mdrun 'MOF'
0 steps,      0.0 ps.

Writing final coordinates.

NOTE: 25 % of the run time was spent in pair search,
      you might want to increase nstlist (this has no effect on accuracy)

               Core t (s)   Wall t (s)        (%)
       Time:       72.006        2.000     3599.4
                 (ns/day)    (hour/ns)
Performance:        0.043      555.689

GROMACS reminds you: "This work contains many things which are new and interesting. Unfortunately, everything that is new is not interesting, and everything which is interesting, is not new." (Lev Landau)

                       :-) GROMACS - gmx dump, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx dump, version 2019.3
Executable:   /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018/bin/gmx_mpi
Data prefix:  /shared/ucl/apps/gromacs/2019.3/plumed/intel-2018
Working dir:  /myriadfs/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/F759D3
Command line:
  gmx_mpi dump -f SP.trr

trr version: GMX_trn_file (single precision)

GROMACS reminds you: "Oh, There Goes Gravity" (Eminem)

CompletedProcess(args=['bash', '-l', '/home/uccaset/Scratch/FFOPTI/data/GF334_v2/classical/D3/run_all'], returncode=0)

## Processing output and adding result to pkl

In [27]:
bob = param

In [29]:
print(param)

{'D1': {'lj':   atom func    mass  charge ptype     sigma  epsilon
0  Zn3    1  65.380     0.0     A  0.246155   0.5188
1  C_2    1  12.011     0.0     A  0.343085   0.4393
2  C_1    1  12.011     0.0     A  0.343085   0.4393
3   H_    1   1.008     0.0     A  0.257113   0.1841
4  N_R    1  14.007     0.0     A  0.326069   0.2887, 'bonds':   atom1 atom2 func  length  force_const
0   Zn3   N_R    1  0.1883    491035.36
1   C_2   C_2    1  0.1444    343088.00
2   C_2   C_1    1  0.1490    334720.00
3   C_1   N_R    1  0.1335    410032.00
4   C_1    H_    1  0.1080    284512.00
5   N_R   N_R    1  0.1320    418400.00, 'angles':   atom1 atom2 func atom3   angle  force_const
0   Zn3   N_R  C_1     1  132.60     1615.840
1   N_R   Zn3  N_R     1  109.47      301.050
2   Zn3   N_R  N_R     1  121.90     1615.840
3   C_1   C_2  C_2     1  112.70      488.273
4   C_2   C_1   H_     1  130.70      292.880
5   C_2   C_1  N_R     1  106.60      585.760
6   C_1   C_2  C_1     1  120.00      527.184
7    H_   C_1  N_R     1  121.60      292.880
8   C_1   N_R  N_R     1  113.40      468.608, 'dihedrals':    atom1 atom2 atom3 atom4 func        T1        T2         T3        T4  \
0    Zn3   N_R   C_1   C_2    3  30.33400   0.00000  -30.33400   0.00000
1    Zn3   N_R   C_1    H_    3  30.33400   0.00000  -30.33400   0.00000
2    N_R   Zn3   N_R   C_1    3   0.00000   0.00000    0.00000   0.00000
3    N_R   N_R   Zn3   N_R    3   0.00000   0.00000    0.00000   0.00000
4    Zn3   N_R   N_R   Zn3    3  30.33400   0.00000  -30.33400   0.00000
5    Zn3   N_R   N_R   C_1    3  30.33400   0.00000  -30.33400   0.00000
6    C_1   C_2   C_2   C_1    3  -4.96013   6.28646    1.30959  -2.63592
7     H_   C_1   C_2   C_2    3   0.96650   2.89951    0.00000  -3.86601
8    N_R   C_1   C_2   C_2    3  -0.76567   2.70705    4.02501  -5.96639
9    C_1   C_2   C_1    H_    3  -0.20920  -0.62760    0.00000   0.83680
10   C_1   C_2   C_1   N_R    3   2.09200   0.00000   -2.09200   0.00000
11   C_2   C_1   N_R   N_R    3   0.72592   2.17777    0.00000  -2.90370
12    H_   C_1   N_R   N_R    3  30.33400   0.00000  -30.33400   0.00000
13   C_1   N_R   N_R   C_1    3  41.84000   0.00000  -41.84000   0.00000

         T5       T6
0   0.00000  0.00000
1   0.00000  0.00000
2   0.00000  0.00000
3   0.00000  0.00000
4   0.00000  0.00000
5   0.00000  0.00000
6   0.00000  0.00000
7   0.00000  0.00000
8   0.00000  0.00000
9   0.00000  0.00000
10  0.00000  0.00000
11  0.00000  0.00000
12  0.00000  0.00000
13  0.00000  0.00000  }, 'D2': {'lj':   atom func    mass  charge ptype     sigma  epsilon
0  Zn3    1  65.380     0.0     A  0.195998  0.05230
1  C_2    1  12.011     0.0     A  0.385000  0.58576
2  C_1    1  12.011     0.0     A  0.355000  0.29288
3   H_    1   1.008     0.0     A  0.250000  0.20920
4  N_R    1  14.007     0.0     A  0.325000  0.71128, 'bonds':   atom1 atom2 func  length  force_const
0   Zn3   N_R    1  0.1883    491035.36
1   C_2   C_2    1  0.1444    343088.00
2   C_2   C_1    1  0.1490    334720.00
3   C_1   N_R    1  0.1335    410032.00
4   C_1    H_    1  0.1080    284512.00
5   N_R   N_R    1  0.1320    418400.00, 'angles':   atom1 atom2 func atom3   angle  force_const
0   Zn3   N_R  C_1     1  132.60     1615.840
1   N_R   Zn3  N_R     1  109.47      301.050
2   Zn3   N_R  N_R     1  121.90     1615.840
3   C_1   C_2  C_2     1  112.70      488.273
4   C_2   C_1   H_     1  130.70      292.880
5   C_2   C_1  N_R     1  106.60      585.760
6   C_1   C_2  C_1     1  120.00      527.184
7    H_   C_1  N_R     1  121.60      292.880
8   C_1   N_R  N_R     1  113.40      468.608, 'dihedrals':    atom1 atom2 atom3 atom4 func        T1        T2         T3        T4  \
0    Zn3   N_R   C_1   C_2    3  30.33400   0.00000  -30.33400   0.00000
1    Zn3   N_R   C_1    H_    3  30.33400   0.00000  -30.33400   0.00000
2    N_R   Zn3   N_R   C_1    3   0.00000   0.00000    0.00000   0.00000
3    N_R   N_R   Zn3   N_R    3   0.00000   0.00000    0.00000   0.00000
4    Zn3   N_R   N_R   Zn3    3  30.33400   0.00000  -30.33400   0.00000
5    Zn3   N_R   N_R   C_1    3  30.33400   0.00000  -30.33400   0.00000
6    C_1   C_2   C_2   C_1    3  -4.96013   6.28646    1.30959  -2.63592
7     H_   C_1   C_2   C_2    3   0.96650   2.89951    0.00000  -3.86601
8    N_R   C_1   C_2   C_2    3  -0.76567   2.70705    4.02501  -5.96639
9    C_1   C_2   C_1    H_    3  -0.20920  -0.62760    0.00000   0.83680
10   C_1   C_2   C_1   N_R    3   2.09200   0.00000   -2.09200   0.00000
11   C_2   C_1   N_R   N_R    3   0.72592   2.17777    0.00000  -2.90370
12    H_   C_1   N_R   N_R    3  30.33400   0.00000  -30.33400   0.00000
13   C_1   N_R   N_R   C_1    3  41.84000   0.00000  -41.84000   0.00000

         T5       T6
0   0.00000  0.00000
1   0.00000  0.00000
2   0.00000  0.00000
3   0.00000  0.00000
4   0.00000  0.00000
5   0.00000  0.00000
6   0.00000  0.00000
7   0.00000  0.00000
8   0.00000  0.00000
9   0.00000  0.00000
10  0.00000  0.00000
11  0.00000  0.00000
12  0.00000  0.00000
13  0.00000  0.00000  }, 'D3': {'lj':   atom func    mass  charge ptype     sigma   epsilon
0  Zn3    1  65.380     0.0     A  0.180759  0.059879
1  C_2    1  12.011     0.0     A  0.367383  0.583853
2  C_1    1  12.011     0.0     A  0.323320  0.265432
3   H_    1   1.008     0.0     A  0.268181  0.169900
4  N_R    1  14.007     0.0     A  0.320617  0.720316, 'bonds':   atom1 atom2 func  length  force_const
0   Zn3   N_R    1  0.1883    491035.36
1   C_2   C_2    1  0.1444    343088.00
2   C_2   C_1    1  0.1490    334720.00
3   C_1   N_R    1  0.1335    410032.00
4   C_1    H_    1  0.1080    284512.00
5   N_R   N_R    1  0.1320    418400.00, 'angles':   atom1 atom2 func atom3   angle  force_const
0   Zn3   N_R  C_1     1  132.60     1615.840
1   N_R   Zn3  N_R     1  109.47      301.050
2   Zn3   N_R  N_R     1  121.90     1615.840
3   C_1   C_2  C_2     1  112.70      488.273
4   C_2   C_1   H_     1  130.70      292.880
5   C_2   C_1  N_R     1  106.60      585.760
6   C_1   C_2  C_1     1  120.00      527.184
7    H_   C_1  N_R     1  121.60      292.880
8   C_1   N_R  N_R     1  113.40      468.608, 'dihedrals':    atom1 atom2 atom3 atom4 func        T1        T2         T3        T4  \
0    Zn3   N_R   C_1   C_2    3  30.33400   0.00000  -30.33400   0.00000
1    Zn3   N_R   C_1    H_    3  30.33400   0.00000  -30.33400   0.00000
2    N_R   Zn3   N_R   C_1    3   0.00000   0.00000    0.00000   0.00000
3    N_R   N_R   Zn3   N_R    3   0.00000   0.00000    0.00000   0.00000
4    Zn3   N_R   N_R   Zn3    3  30.33400   0.00000  -30.33400   0.00000
5    Zn3   N_R   N_R   C_1    3  30.33400   0.00000  -30.33400   0.00000
6    C_1   C_2   C_2   C_1    3  -4.96013   6.28646    1.30959  -2.63592
7     H_   C_1   C_2   C_2    3   0.96650   2.89951    0.00000  -3.86601
8    N_R   C_1   C_2   C_2    3  -0.76567   2.70705    4.02501  -5.96639
9    C_1   C_2   C_1    H_    3  -0.20920  -0.62760    0.00000   0.83680
10   C_1   C_2   C_1   N_R    3   2.09200   0.00000   -2.09200   0.00000
11   C_2   C_1   N_R   N_R    3   0.72592   2.17777    0.00000  -2.90370
12    H_   C_1   N_R   N_R    3  30.33400   0.00000  -30.33400   0.00000
13   C_1   N_R   N_R   C_1    3  41.84000   0.00000  -41.84000   0.00000

         T5       T6
0   0.00000  0.00000
1   0.00000  0.00000
2   0.00000  0.00000
3   0.00000  0.00000
4   0.00000  0.00000
5   0.00000  0.00000
6   0.00000  0.00000
7   0.00000  0.00000
8   0.00000  0.00000
9   0.00000  0.00000
10  0.00000  0.00000
11  0.00000  0.00000
12  0.00000  0.00000
13  0.00000  0.00000  }}

In [31]:
#calculating the loss for the new output
d_folder = f'{GMX_ref_path}/{new_D}'
single_calc_tools = single_loss_calc(Structure_name,Structure, DFT_ref_path,d_folder)

In [32]:
new_loss = single_calc_tools.average_type_loss_per_D()

Extracted forces from 100 frames.
Extracted forces from 100 frames.

In [33]:
new_loss

             3
Zn3  49.140344
C_2   0.735957
C_1   5.486122
H_    0.053464
N_R  36.817142

In [42]:
average_loss = average_loss.join(new_loss)

In [ ]:
average_loss.to_pickle(f"{GMX_ref_path}/ffopti_backup/param_type_loss.pkl")

In [43]:
len(average_loss.columns)

3